### ISSUE TITLE
run server failed

### ISSUE THREAD

**Issue by jerrytesting** [tikv/pd#6270] opened 2023-04-05 02:10 UTC
### What did you do?
Run Jepsen test configured with kill, pause and partition nemesis

### What did you expect to see?
No fatal

### What did you see instead?
we found fatal. The following is the log history:
`./20230316T152153.412Z/n3/pd.log:[2023/03/16 15:28:27.056 +00:00] [FATAL] [main.go:117] ["run server failed"] [error="[PD:etcd:ErrEtcdKVGet]rpc error: code = Unknown desc = context deadline exceeded: rpc error: code = Unknown desc = context deadline exceeded"] [stack="main.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/cmd/pd-server/main.go:117\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"]`

### What version of PD are you using (`pd-server -V`)?
v6.1.2

**Comment by rleungx** [comment] 2023-07-21 08:55
Could you please provide more details about the test? From the log, it looks like there is something wrong when PD tries to read from etcd.

**Comment by rleungx** [comment] 2023-09-07 07:00
I cannot reproduce it locally and I'm going to close this issue since there is no more information to do the investigation. feel free to reopen it if the problem still exists.

**Closed by rleungx** 2023-09-07 07:00 UTC
Labels: type/bug
