### ISSUE TITLE
Error TLS handshake

### ISSUE THREAD

**Issue by mickar** [tikv/pd#2569] opened 2020-06-22 09:18 UTC
Hello,

## Bug Report

When I try to start PD cluster with TLS enable through default ports 2379 and 2380. I got this :

```
[config_logging.go:279] ["rejected connection"] [remote-addr=192.168.10.182:59934] [server-name=] [error="tls: first record does not look like a TLS handshake"]
[config_logging.go:279] ["rejected connection"] [remote-addr=192.168.10.183:59940] [server-name=] [error="tls: first record does not look like a TLS handshake"]
```

This error is present on all nodes. The current version in my test is 4.0.0.

```
pd-server --version
Release Version: v4.0.0
Edition: Community
Git Commit Hash: 56d4c3d2237f5bf6fb11a794731ed1d95c8020c2
Git Branch: heads/refs/tags/v4.0.0
UTC Build Time:  2020-05-28 01:39:35
```

### What did you do?

I have 3 nodes :

- 192.168.10.181
- 192.168.10.182
- 192.168.10.183

I tried to start the cluster in 2 ways

The first one is with Docker :

```
#!/bin/bash

NAME_1=pd1.test.net
HOST_1=192.168.10.181
NAME_2=pd2.test.net
HOST_2=192.168.10.182
NAME_3=pd3.test.net
HOST_3=192.168.10.183

CULSTER_PORT=2380

CLUSTER="${NAME_1}=https://${HOST_1}:${CULSTER_PORT},${NAME_2}=https://${HOST_2}:${CULSTER_PORT},${NAME_3}=https://${HOST_3}:${CULSTER_PORT}"

THIS_NAME=pd1.test.net
THIS_IP=192.168.10.181

docker create --name test-pd --network=host \
        -v /SSD/pd/data:/data \
        -v /etc/localtime:/etc/localtime:ro \
        -v /root/pingcap_cluster_cert:/root/pingcap_cluster_cert:ro \
        -v /root/test-pd/etc:/etc/pd \
        -v /root/test-pd/log:/log \
        pingcap/pd:v4.0.0 \
        -data-dir /data \
        -config /etc/pd/pd.toml \
        -name="${THIS_NAME}" \
        -client-urls="https://${THIS_IP}:2379" \
        -advertise-client-urls="https://${THIS_IP}:2379" \
        -peer-urls="https://${THIS_IP}:2380" \
        -advertise-peer-urls="https://${THIS_IP}:2380" \
        -log-file /log/pd.log \
        -initial-cluster=${CLUSTER}
```

and with SystemD :

```
pd-server \
    --name="pd-192.168.10.181-2379" \
    --client-urls="https://192.168.10.181:2379" \
    --advertise-client-urls="https://192.168.10.181:2379" \
    --peer-urls="https://192.168.10.181:2380" \
    --advertise-peer-urls="https://192.168.10.181:2380" \
    --data-dir="/SSD/pd/data" \
    --initial-cluster="pd-192.168.10.181-2379=https://192.168.10.181:2380,pd-192.168.10.182-2379=https://192.168.10.182:2380,pd-192.168.10.183-2379=https://192.168.10.183:2380" \
    --config=conf/pd.toml \
    --log-file="/root/test-pd/log/pd.log" 2>> "/root/test-pd/log/pd_stderr.log"
```

I followed these tutorials to generate certificates :

- https://pingcap.com/docs/stable/enable-tls-between-components/
- https://pingcap.com/docs/stable/generate-self-signed-certificates/

and :

- https://pingcap.com/docs/v3.1/generate-self-signed-certificates/
- https://pingcap.com/docs/v3.1/enable-tls-between-components/

I also tried with Let's encrypt certificates with my domain.

The config file (/etc/pd/pd.toml) is :

```
[replication]
enable-placement-rules = true
location-labels = ["zone", "dc", "host"]
max-replicas = 3

[security]
cert-path="/root/pingcap_cluster_cert/PD-Server-cert.pem"
key-path="/root/pingcap_cluster_cert/PD-Server-key.pem"
cacert-path="/root/pingcap_cluster_cert/ca-cert.pem"
```

Best regards,

**Comment by HunDunDM** [comment] 2020-06-23 03:10
Have you started the cluster in a non-TLS form before?

**Comment by mickar** [comment] 2020-06-23 08:44
Hello,
Thank you for your reply.
It's true, I tried without certificates before. I forget to explain this detail in my ticket.
I tried to start with another data directory and the PD cluster is working properly.
I would like to use TiUP to manage my cluster, but I have not yet seen the possibility to activate TLS. So I tried to start an existing cluster manually with TLS enable for testing.
Is it not possible to activate TLS when we have an existing cluster?
So, it might be better not to use TiUP when the TLS property is not offered ?
Best regards,

**Comment by nolouch** [comment] 2020-08-24 03:52
Hi, @mickar  there is an issue https://github.com/pingcap/tiup/issues/529 about supports TLS with tiup. you can follow this issue, I'm going to close this issue.

**Closed** 2020-08-24 03:53 UTC
Labels: type/bug

**Comment by haichu1997** [comment] 2024-03-01 02:42
@mickar hello. 
Please tell me what is the cause of this error?
old version, right?
Thank you very much

**Comment by haichu1997** [comment] 2024-03-01 02:45
@nolouch  hello.
Please tell me what is the cause of this error?
old version, right?
Thank you very much

I install tikv refer "https://tikv.org/docs/7.1/deploy/install/test" and well is verison 5.0.1
