### ISSUE TITLE
"total_written_bytes_as_peer" statistic the total store rather than hot peer

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#2989] opened 2020-09-18 06:30 UTC
### What did you do?

observe hot statstic 

### What did you expect to see?

![image](https://user-images.githubusercontent.com/19542290/93563793-2d27b900-f9bb-11ea-9cea-d5b1a14e0cf6.png)

total_written_bytes_as_peer is zero when hot peer is zero 

### What did you see instead?

total_written_bytes_as_peer is equal with store written bytes. it only fits its definition when it is written leader

```
                       for _, peer := range filterHotPeers(kind, minHotDegree, hotRegionThreshold, storeHotPeers[id], hotPeerFilterTy) {
				byteSum += peer.GetByteRate()
				keySum += peer.GetKeyRate()
				hotPeers = append(hotPeers, peer.Clone())
			}
			// Use sum of hot peers to estimate leader-only byte rate.
			if kind == core.LeaderKind && rwTy == write {
				byteRate = byteSum
				keyRate = keySum
			}
```

### What version of PD are you using (`pd-server -V`)?

master

**Comment by nolouch** [comment] 2020-09-19 09:24
I think it's not a bug, we should improve the metrics name.

**Comment by rleungx** [comment] 2021-10-18 10:32
Closed by https://github.com/tikv/pd/pull/3726

**Closed by rleungx** 2021-10-18 10:32 UTC
Labels: type/enhancement
