### ISSUE TITLE
The region statistic does not match the hot read statistics

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#3245] opened 2020-12-02 02:56 UTC
### What did you do?

Run sysbench read_only workload.

### What did you expect to see?

The hot region is balanced and the number of the hot regions is almost the same.

### What did you see instead?

From the `hot read` in pd-ctl:
```
"104": {
    "total_flow_bytes": 12236445.15,
    "total_flow_keys": 50156.25,
    "regions_count": 1,
    "statistics": [
        {
            "store_id": 104,
            "region_id": 186247997,
            "hot_degree": 566,
            "anti_count": 2,
            "kind": 1,
            "flow_bytes": 12092750.38095238,
            "flow_keys": 49560.45238095238,
            "RollingByteRate": null,
            "RollingKeyRate": null,
            "last_update_time": "2020-12-02T02:50:43.921713736Z",
            "version": 129
        }
    ]
}
```

We find there is only one hot region in store 104 and the region id is 186247997.

Use pd-ctl `region 186247997`:
```
{
  "id": 186247997,
  "start_key": "7480000000000000FFA55F728000000000FF0013C60000000000FA",
  "end_key": "7480000000000000FFA55F728000000000FF00140C0000000000FA",
  "epoch": {
    "conf_ver": 77,
    "version": 129
  },
  "peers": [
    {
      "id": 186247998,
      "store_id": 1
    },
    {
      "id": 186247999,
      "store_id": 104
    },
    {
      "id": 186248000,
      "store_id": 66
    }
  ],
  "leader": {
    "id": 186247999,
    "store_id": 104
  },
  "written_bytes": 0,
  "read_bytes": 0,
  "written_keys": 0,
  "read_keys": 0,
  "approximate_size": 1,
  "approximate_keys": 0
}
```

### What version of PD are you using (`pd-server -V`)?
master

**Comment by lhy1024** [comment] 2020-12-02 04:45
The reason of the difference between `region` and `hot-region` is that `saveCache` is false.

![image](https://user-images.githubusercontent.com/19542290/100829292-f2063380-349b-11eb-9fa0-465c820f3055.png)

And we can observe their update timestamp are different.

![image](https://user-images.githubusercontent.com/19542290/100829333-0fd39880-349c-11eb-91d5-cab8109383cc.png)
![image](https://user-images.githubusercontent.com/19542290/100829351-1d891e00-349c-11eb-8374-96a96a920007.png)

**Comment by HunDunDM** [comment] 2020-12-02 09:28
The statistics in the cache are not updated when `trace-region-flow` is `false`, which is the expected behavior.

**Comment by lhy1024** [comment] 2020-12-02 09:58
it may be better not to display the flow rate. if `trace-region-flow` is `false`

**Comment by HunDunDM** [comment] 2020-12-02 10:02
If you are not actively setting it, it should be caused by this #3116 .

**Comment by HunDunDM** [comment] 2020-12-02 10:03
> it may be better not to display the flow rate. if `trace-region-flow` is `false`

lgtm

**Comment by nolouch** [comment] 2020-12-07 04:11
so ss it already fixed? @HunDunDM @lhy1024

**Comment by lhy1024** [comment] 2020-12-07 04:20
> so ss it already fixed? @HunDunDM @lhy1024

I think we can close this issue, and open another about fixing the display

**Closed** 2020-12-07 04:23 UTC
Labels: severity/minor, type/bug

**Comment by rleungx** [comment] 2020-12-07 05:50
Why do we need to close this issue and open another one?
