### ISSUE TITLE
TestReconnect is unstable

### ISSUE THREAD

**Issue by HuSharp** [tikv/pd#7104] opened 2023-09-18 02:06 UTC
## Flaky Test
TestReconnect

### Which jobs are failing
```
2023-09-18T02:01:41.0373195Z --- FAIL: TestReconnect (25.94s)
2023-09-18T02:01:41.0373387Z     testutil.go:64: 
2023-09-18T02:01:41.0373878Z         	Error Trace:	/home/runner/work/pd/pd/pkg/utils/testutil/testutil.go:64
2023-09-18T02:01:41.0374721Z         	            				/home/runner/work/pd/pd/tests/server/api/api_test.go:100
2023-09-18T02:01:41.0375025Z         	Error:      	Condition never satisfied
2023-09-18T02:01:41.0375256Z         	Test:       	TestReconnect
```

### CI link
https://github.com/tikv/pd/actions/runs/6217309729/job/16872225487?pr=7092

**Comment by lhy1024** [comment] 2023-11-06 04:34
again https://github.com/tikv/pd/actions/runs/6766179778/job/18387177759?pr=7315

**Comment by lhy1024** [comment] 2023-11-07 06:47
again https://github.com/tikv/pd/actions/runs/6780769115/job/18429944487?pr=7278

**Comment by HuSharp** [comment] 2023-11-10 05:23
again https://github.com/tikv/pd/actions/runs/6813646583/job/18528713451?pr=7344

**Comment by rleungx** [comment] 2024-04-15 09:18
Cannot reproduce it in my local environment, close this issue for now. If it happens again, please reopen it.

**Closed by rleungx** 2024-04-15 09:18 UTC
Labels: type/ci

**Comment by okJiang** [comment] 2026-04-14 21:35
New CI link:
- https://github.com/tikv/pd/actions/runs/24404050527/job/71282535346

**Comment by okJiang** [comment] 2026-05-12 21:15
### New CI link
- https://prow.tidb.net/view/gs/prow-tidb-logs/pr-logs/pull/tikv_pd/10665/pull-unit-test-next-gen-2/2054089881923096576

- PR: #10665

**Comment by okJiang** [comment] 2026-05-18 21:46
- https://prow.tidb.net/view/gs/prow-tidb-logs/pr-logs/pull/tikv_pd/10685/pull-unit-test-next-gen-2/2056218925930123264

**Comment by okJiang** [comment] 2026-05-20 21:24
New CI links:
- https://prow.tidb.net/view/gs/prow-tidb-logs/pr-logs/pull/tikv_pd/10689/pull-unit-test-next-gen-2/2057019103943593984
- https://prow.tidb.net/view/gs/prow-tidb-logs/pr-logs/pull/tikv_pd/10689/pull-unit-test-next-gen-2/2057026959669465088
