### ISSUE TITLE
 After Placement rules, config set max-replica setting problem

### ISSUE THREAD

**Issue by together-wang** [tikv/pd#3893] opened 2021-07-21 07:44 UTC
### What did you do?
When Placement Rules is turned on, the config set max-replicas is adjusted from 3 to 5 successfully but it does not actually take effect. Change from 5 to 3 prompts an error.

### What did you expect to see?
When Placement Rules is turned on, an error is reported through config set max-replicas, prompting the user to use the interface to modify

### What did you see instead?
![image](https://user-images.githubusercontent.com/44355590/126448439-0b6f0ebb-d7a6-4452-8aaa-c1dea2cefcdd.png)

### What version of PD are you using (`pd-server -V`)?
![image](https://user-images.githubusercontent.com/44355590/126450257-61e7c79a-9798-4ad4-851b-fc4119e8b5b2.png)

**Comment by mayjiang0203** [comment] 2021-07-22 03:17
Duplicate of #3886 
Same root cause with #3886, and the fix of #3886 will fix this issue also, so mark it as duplicate.

**Comment by mayjiang0203** [comment] 2021-07-22 03:20
Same root cause with #3886, and the fix of #3886 will fix this issue also, so mark it as duplicate.

**Comment by nolouch** [comment] 2021-07-28 04:00
It is fixed in master. you can try the master first.

**Closed by nolouch** 2021-07-28 04:00 UTC
Labels: type/bug
