### ISSUE TITLE
After restarting another TiKV process during the shrinking a TiKV, the duration increase more

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#3796] opened 2021-06-17 10:35 UTC
### What did you do?

1. deploy a v5.1.0 tidb cluster with 3pd 8db 30kv.
2. run workload and shrinking a TiKV
![缩容负载](https://user-images.githubusercontent.com/84712107/122379233-3de07c00-cf99-11eb-8b93-5571bd08d37a.png)

3. while shrinking a TiKV， restarting another TiKV process 
<img width="1846" alt="大集群缩容的节点" src="https://user-images.githubusercontent.com/84712107/122380144-25bd2c80-cf9a-11eb-94fd-707658ebc5d9.png">

### What did you expect to see?
The duration is relatively stable

### What did you see instead?
the duration increase more
![大集群缩容复位节点](https://user-images.githubusercontent.com/84712107/122379395-69636680-cf99-11eb-962a-8eb7e70fbb5a.png)

### What version of PD are you using (`pd-server -V`)?
[root@IDC-172-16-6-7 pd-2379]# bin/pd-server -V
Release Version: v5.1.0-alpha-28-gf6b61bad-dirty
Edition: Community
Git Commit Hash: f6b61bad356a053f6e934c93a62376c27f0858e8
Git Branch: release-5.1-hotfix
UTC Build Time:  2021-06-10 06:33:51

**Comment by youjiali1995** [comment] 2021-06-21 10:59
It's caused by backup...
![image](https://user-images.githubusercontent.com/14819777/122751645-9d54c980-d2c2-11eb-85b8-e24f1cd6a614.png)

**Comment by nolouch** [comment] 2021-06-22 02:42
According @youjiali1995 , I remove the bug label first.

**Comment by tisonkun** [comment] 2021-06-25 05:38
@nolouch If it is not a bug, and I don't see there is question to be answered, shall we close this issue as invalid?

**Comment by rleungx** [comment] 2021-12-10 08:34
Close it since it is caused by backup according to @youjiali1995 said.

**Closed by rleungx** 2021-12-10 08:34 UTC
Labels: type/question
